{
 "title": "SSL Certificates",
 "description": "Simple dashboard for amimof/node-cert-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Expiration within 10 days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssl_certificate_days_left <= 10) OR on() vector(0)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "\n(sum(last_over_time(ssl_certificate_days_left{}[1m])  ) by (domain, alias, ip)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expiration within month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssl_certificate_days_left <= 00) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Last successful run ssl checker",
   "type": "stat",
   "description": "### Last successful run ssl checker \nShows how long it has been since\nits last successful checking run.\n\nThe value in the status panel is based on how long it has been since the last successful compaction.\n\n- Okay: less than 24 hours\n- Late: more than 48 hours\n- Very late: more than 72 hours \n\nIf the status of ssl checker are *Late* or *Very late*, check their health. It's critical status.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - max_over_time(ssl_certificate_last_successful_run{}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}